version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANJSON3Project
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
